version: '2'
services:
  bootstrapernode:
    image: pmarches/peercentrum
    volumes:
      - ./permanentMockNetwork.testdata/connectingNode/:/runtime
    ports:
      - "35460:35460"

  node1:
    image: pmarches/peercentrum
    volumes:
      - ./permanentMockNetwork.testdata/node1/:/runtime
    depends_on:
      - bootstrapernode

  node2:
    image: pmarches/peercentrum
    volumes:
      - ./permanentMockNetwork.testdata/node2/:/runtime
    depends_on:
      - bootstrapernode
