!!org.peercentrum.core.TopLevelConfig
listenPort: 0    #Set to 0 to select any open port at startup
enableNAT: false
encryptConnection: true #For debugging purposes only
applications: 
  - !!org.peercentrum.core.nodegossip.NodeGossipConfig
    bootstrapEndpoint: 03BAD67F48C7B7F50CDFE234A4E5CCE652182D880482B83A45DF2921115B7C0ED4:bootstrapernode:35460

  - !!org.peercentrum.blob.P2PBlobConfig
    #maximumStorageAllowed: 100M
    transferPricingPerGigabyte: 16129 #About 0.10 USD per GB (amazon charges 0.12)
